### ISSUE TITLE
MenuBar not responsive after application start

### ISSUE THREAD

**Issue by stephansann** [0x4a616e/NSMenuFX#15]
Hello!

I included NSMenuFX in my application.
After the start of the application the MenuBar is not responsive (does not respond to any clicks).
Only after changing back-and-forth to another app and then to my app again the MenuBar will eventually respond.

I was able to reproduce the behavior with the SampleApp (de.jangassen.nsmenufx.samples.SampleMenuBar).

Environment is macOS Big Sur (v11.2.3), AdoptOpenJDK 11.0.10+9. See screenshot for JavaFX libs.

Any ideas?

Thanks and best regards
Stephan

<img width="516" alt="Screen Shot 2021-04-11 at 10 46 55" src="https://user-images.githubusercontent.com/9678681/114297841-4efda000-9ab3-11eb-80ce-8b6ae3462462.png">

**Comment by 0x4a616e** [comment]
That seems to be a JDK issue, you can find more details here: https://github.com/0x4a616e/NSMenuFX/issues/8

**Comment by stephansann** [comment]
Ah - thanks for the info.
Maybe it would be good to put this into the README!? There is already a chapter "Known issues".

**Comment by 0x4a616e** [comment]
That's actually a good point! Will do that 👍

**Comment by 0x4a616e** [comment]
There it is: https://github.com/0x4a616e/NSMenuFX#known-issues
