### ISSUE TITLE
setAccelerator() not working as expected

### ISSUE THREAD

**Issue by vewert** [0x4a616e/NSMenuFX#5]
I create a Preferences... menu item as follows:

```
final MenuItem preferencesMenuItem = new MenuItem("Preferences...");
preferencesMenuItem.setAccelerator(new KeyCodeCombination(KeyCode.COMMA, KeyCodeCombination.META_DOWN));
preferencesMenuItem.setOnAction(this::handleOptionsMenuItemAction);
```

When the menu is displayed, however, the accelerator shows as ⌘C (see screen shot)

![2020-12-01_10-55-40](https://user-images.githubusercontent.com/38388418/100785539-a2553880-33c5-11eb-9201-f57ec39d1738.png)

It works as expected, using the older version (2.18) i.e should be ⌘, (which is the expected key combination on Mac)

**Comment by 0x4a616e** [comment]
Ouch, that looks like a bug in the mapping between JavaFX KeyAccelerators and AppKit keyEquivalents. That should be fixed soon!

**Comment by 0x4a616e** [comment]
Fix is there: https://github.com/0x4a616e/NSMenuFX/commit/6c446a29192277db637b98047ee4f9f182e0f210 release 3.0.1 is incoming 😉

**Comment by vewert** [comment]
You are amazing! I grabbed 3.0.1, and that fixes the problem.

Thanks!
