### ISSUE TITLE
MenuBar not working on launch

### ISSUE THREAD

**Issue by twiedow** [0x4a616e/NSMenuFX#8]
I have the same issue like described here:
https://stackoverflow.com/questions/22569046/how-to-make-an-os-x-menubar-in-javafx/39627830#39627830

I cannot open the menu bar until I switch to another app and back to my JavaFX app. Then everything works as expected.

Do you have an idea what the problem is here?

I use OpenJDK 15 and JavaFX 15. I add a default app menu like this:

```
            var tk = MenuToolkit.toolkit();
            var defaultApplicationMenu = tk.createDefaultApplicationMenu("BCM");
            tk.setApplicationMenu(defaultApplicationMenu);
```

Then on a stage I'm adding a menu bar like this:

```
        var fileMenu = MenuBarUtil.createMenu(MenuType.file);
        MenuBarUtil.addMenuItemToMenu(fileMenu, MenuItemType.fileClose, this::close);

        var menuBar = new MenuBar();
        menuBar.setUseSystemMenuBar(true);
        menuBar.getMenus().add(fileMenu);

        gridPane.add(menuBar, 0, 0);
```

The helper class just adds some menu items with some key code combinations as accelerators.

**Comment by 0x4a616e** [comment]
Hi @twiedow, thanks for the report. That seems to be a JavaFX-related issue and might not have something to do with NSMenuFX: https://bugs.openjdk.java.net/browse/JDK-8233678 Can you maybe check if the same issue is also occurring without NSMenuFX?

**Comment by vewert** [comment]
I had noticed a similar behaviour, but only when running through the IDE (IntelliJ). In my case, however, after building it into a mac .app and running it, the menu seemed to work fine. Note: I use https://github.com/beryx/badass-jlink-plugin (which uses jlink and jpackage) to build it into a mac app.

**Comment by 0x4a616e** [comment]
I have the same issue when I run the application from IntelliJ. But for me, this happens regardless of wether or not I use NSMenuFX... So to me it looks like this issue is rooted somewhere in JFX 😞

**Comment by 0x4a616e** [comment]
The respective PR was merged just a few days ago: https://github.com/openjdk/jfx/pull/361
So I hope we'll see a fix soon.
